from Src.Enums.activations import Activations
from Src.Enums.padding import Padding
from Src.Enums.colormode import ColorMode
from Src.Enums.attr_type import AttrType
from Src.Enums.losses import Losses
from Src.Enums.optimizers import Optimizers
from Src.Enums.delimiters import Delimiters
from Src.Enums.dpg_types import DPGType
from Src.Enums.metrics import Metrics
from Src.Enums.themes import Themes
from Src.Enums.datasets import Datasets