from enum import Enum

import dearpygui.dearpygui as dpg




class DPGType(Enum):
    """
    Enum для элементов dearpygui
    """

    @classmethod
    def _missing_(cls, value: str | int):
        return cls(dpg.get_item_type(value))
    
    # Основные виджеты
    BUTTON = 'mvAppItemType::mvButton'
    CHECKBOX = 'mvAppItemType::mvCheckbox'
    COMBO = 'mvAppItemType::mvCombo'
    DRAG_FLOAT = 'mvAppItemType::mvDragFloat'
    DRAG_INT = 'mvAppItemType::mvDragInt'
    DRAG_DOUBLE = 'mvAppItemType::mvDragDouble'
    DRAG_FLOAT_MULTI = 'mvAppItemType::mvDragFloatMulti'
    DRAG_INT_MULTI = 'mvAppItemType::mvDragIntMulti'
    DRAG_DOUBLE_MULTI = 'mvAppItemType::mvDragDoubleMulti'
    INPUT_TEXT = 'mvAppItemType::mvInputText'
    INPUT_INT = 'mvAppItemType::mvInputInt'
    INPUT_FLOAT = 'mvAppItemType::mvInputFloat'
    INPUT_DOUBLE = 'mvAppItemType::mvInputDouble'
    INPUT_INT_MULTI = 'mvAppItemType::mvInputIntMulti'
    INPUT_FLOAT_MULTI = 'mvAppItemType::mvInputFloatMulti'
    INPUT_DOUBLE_MULTI = 'mvAppItemType::mvInputDoubleMulti'
    LISTBOX = 'mvAppItemType::mvListbox'
    MENU_ITEM = 'mvAppItemType::mvMenuItem'
    RADIO_BUTTON = 'mvAppItemType::mvRadioButton'
    SELECTABLE = 'mvAppItemType::mvSelectable'
    SLIDER_FLOAT = 'mvAppItemType::mvSliderFloat'
    SLIDER_INT = 'mvAppItemType::mvSliderInt'
    SLIDER_DOUBLE = 'mvAppItemType::mvSliderDouble'
    SLIDER_FLOAT_MULTI = 'mvAppItemType::mvSliderFloatMulti'
    SLIDER_INT_MULTI = 'mvAppItemType::mvSliderIntMulti'
    SLIDER_DOUBLE_MULTI = 'mvAppItemType::mvSliderDoubleMulti'
    SLIDER_3D = 'mvAppItemType::mvSlider3D'
    TEXT = 'mvAppItemType::mvText'
    TREE_NODE = 'mvAppItemType::mvTreeNode'
    TAB_BUTTON = 'mvAppItemType::mvTabButton'
    SEPARATOR = 'mvAppItemType::mvSeparator'
    SPACER = 'mvAppItemType::mvSpacer'
    PROGRESS_BAR = 'mvAppItemType::mvProgressBar'
    KNOB_FLOAT = 'mvAppItemType::mvKnobFloat'
    LOADING_INDICATOR = 'mvAppItemType::mvLoadingIndicator'

    # Изображения и цвета
    IMAGE = 'mvAppItemType::mvImage'
    IMAGE_BUTTON = 'mvAppItemType::mvImageButton'
    COLOR_BUTTON = 'mvAppItemType::mvColorButton'
    COLOR_EDIT = 'mvAppItemType::mvColorEdit'
    COLOR_PICKER = 'mvAppItemType::mvColorPicker'
    COLOR_MAP = 'mvAppItemType::mvColorMap'
    COLOR_MAP_BUTTON = 'mvAppItemType::mvColorMapButton'
    COLOR_MAP_SLIDER = 'mvAppItemType::mvColorMapSlider'
    COLOR_MAP_SCALE = 'mvAppItemType::mvColorMapScale'
    COLOR_MAP_REGISTRY = 'mvAppItemType::mvColorMapRegistry'

    # Дата и время
    DATE_PICKER = 'mvAppItemType::mvDatePicker'
    TIME_PICKER = 'mvAppItemType::mvTimePicker'

    # Контейнеры
    WINDOW_APP_ITEM = 'mvAppItemType::mvWindowAppItem'
    CHILD_WINDOW = 'mvAppItemType::mvChildWindow'
    COLLAPSING_HEADER = 'mvAppItemType::mvCollapsingHeader'
    CLIPPER = 'mvAppItemType::mvClipper'
    FILTER_SET = 'mvAppItemType::mvFilterSet'
    GROUP = 'mvAppItemType::mvGroup'
    MENU = 'mvAppItemType::mvMenu'
    MENU_BAR = 'mvAppItemType::mvMenuBar'
    VIEWPORT_MENU_BAR = 'mvAppItemType::mvViewportMenuBar'
    TAB = 'mvAppItemType::mvTab'
    TAB_BAR = 'mvAppItemType::mvTabBar'
    TOOLTIP = 'mvAppItemType::mvTooltip'
    STAGE = 'mvAppItemType::mvStage'
    TEMPLATE_REGISTRY = 'mvAppItemType::mvTemplateRegistry'

    # Таблицы
    TABLE = 'mvAppItemType::mvTable'
    TABLE_COLUMN = 'mvAppItemType::mvTableColumn'
    TABLE_ROW = 'mvAppItemType::mvTableRow'
    TABLE_CELL = 'mvAppItemType::mvTableCell'

    # Построение графиков
    PLOT = 'mvAppItemType::mvPlot'
    SUBPLOTS = 'mvAppItemType::mvSubPlots'
    SIMPLE_PLOT = 'mvAppItemType::mvSimplePlot'
    PLOT_AXIS = 'mvAppItemType::mvPlotAxis'
    PLOT_LEGEND = 'mvAppItemType::mvPlotLegend'
    ANNOTATION = 'mvAppItemType::mvAnnotation'
    DRAG_LINE = 'mvAppItemType::mvDragLine'
    DRAG_POINT = 'mvAppItemType::mvDragPoint'
    DRAG_RECT = 'mvAppItemType::mvDragRect'
    AXIS_TAG = 'mvAppItemType::mvAxisTag'

    # Серии данных для графиков
    LINE_SERIES = 'mvAppItemType::mvLineSeries'
    SCATTER_SERIES = 'mvAppItemType::mvScatterSeries'
    STEM_SERIES = 'mvAppItemType::mvStemSeries'
    STAIR_SERIES = 'mvAppItemType::mvStairSeries'
    BAR_SERIES = 'mvAppItemType::mvBarSeries'
    BAR_GROUP_SERIES = 'mvAppItemType::mvBarGroupSeries'
    ERROR_SERIES = 'mvAppItemType::mvErrorSeries'
    HEAT_SERIES = 'mvAppItemType::mvHeatSeries'
    IMAGE_SERIES = 'mvAppItemType::mvImageSeries'
    PIE_SERIES = 'mvAppItemType::mvPieSeries'
    SHADE_SERIES = 'mvAppItemType::mvShadeSeries'
    LABEL_SERIES = 'mvAppItemType::mvLabelSeries'
    CANDLE_SERIES = 'mvAppItemType::mvCandleSeries'
    AREA_SERIES = 'mvAppItemType::mvAreaSeries'
    HISTOGRAM_SERIES = 'mvAppItemType::mvHistogramSeries'
    DIGITAL_SERIES = 'mvAppItemType::mvDigitalSeries'
    TWO_D_HISTOGRAM_SERIES = 'mvAppItemType::mv2dHistogramSeries'
    INFINITE_LINE_SERIES = 'mvAppItemType::mvInfLineSeries'
    CUSTOM_SERIES = 'mvAppItemType::mvCustomSeries'

    # Редактор узлов
    NODE_EDITOR = 'mvAppItemType::mvNodeEditor'
    NODE = 'mvAppItemType::mvNode'
    NODE_ATTRIBUTE = 'mvAppItemType::mvNodeAttribute'
    NODE_LINK = 'mvAppItemType::mvNodeLink'

    # Рисование
    DRAWLIST = 'mvAppItemType::mvDrawlist'
    VIEWPORT_DRAWLIST = 'mvAppItemType::mvViewportDrawlist'
    DRAW_LAYER = 'mvAppItemType::mvDrawLayer'
    DRAW_NODE = 'mvAppItemType::mvDrawNode'
    DRAW_LINE = 'mvAppItemType::mvDrawLine'
    DRAW_ARROW = 'mvAppItemType::mvDrawArrow'
    DRAW_TRIANGLE = 'mvAppItemType::mvDrawTriangle'
    DRAW_IMAGE_QUAD = 'mvAppItemType::mvDrawImageQuad'
    DRAW_CIRCLE = 'mvAppItemType::mvDrawCircle'
    DRAW_ELLIPSE = 'mvAppItemType::mvDrawEllipse'
    DRAW_BEZIER_CUBIC = 'mvAppItemType::mvDrawBezierCubic'
    DRAW_BEZIER_QUADRATIC = 'mvAppItemType::mvDrawBezierQuadratic'
    DRAW_QUAD = 'mvAppItemType::mvDrawQuad'
    DRAW_RECT = 'mvAppItemType::mvDrawRect'
    DRAW_TEXT = 'mvAppItemType::mvDrawText'
    DRAW_POLYGON = 'mvAppItemType::mvDrawPolygon'
    DRAW_POLYLINE = 'mvAppItemType::mvDrawPolyline'
    DRAW_IMAGE = 'mvAppItemType::mvDrawImage'

    # Обработчики событий
    HANDLER_REGISTRY = 'mvAppItemType::mvHandlerRegistry'
    ITEM_HANDLER_REGISTRY = 'mvAppItemType::mvItemHandlerRegistry'
    KEY_DOWN_HANDLER = 'mvAppItemType::mvKeyDownHandler'
    KEY_PRESS_HANDLER = 'mvAppItemType::mvKeyPressHandler'
    KEY_RELEASE_HANDLER = 'mvAppItemType::mvKeyReleaseHandler'
    MOUSE_MOVE_HANDLER = 'mvAppItemType::mvMouseMoveHandler'
    MOUSE_WHEEL_HANDLER = 'mvAppItemType::mvMouseWheelHandler'
    MOUSE_CLICK_HANDLER = 'mvAppItemType::mvMouseClickHandler'
    MOUSE_DOUBLE_CLICK_HANDLER = 'mvAppItemType::mvMouseDoubleClickHandler'
    MOUSE_DOWN_HANDLER = 'mvAppItemType::mvMouseDownHandler'
    MOUSE_RELEASE_HANDLER = 'mvAppItemType::mvMouseReleaseHandler'
    MOUSE_DRAG_HANDLER = 'mvAppItemType::mvMouseDragHandler'
    HOVER_HANDLER = 'mvAppItemType::mvHoverHandler'
    ACTIVE_HANDLER = 'mvAppItemType::mvActiveHandler'
    FOCUS_HANDLER = 'mvAppItemType::mvFocusHandler'
    VISIBLE_HANDLER = 'mvAppItemType::mvVisibleHandler'
    EDITED_HANDLER = 'mvAppItemType::mvEditedHandler'
    ACTIVATED_HANDLER = 'mvAppItemType::mvActivatedHandler'
    DEACTIVATED_HANDLER = 'mvAppItemType::mvDeactivatedHandler'
    DEACTIVATED_AFTER_EDIT_HANDLER = 'mvAppItemType::mvDeactivatedAfterEditHandler'
    TOGGLED_OPEN_HANDLER = 'mvAppItemType::mvToggledOpenHandler'
    CLICKED_HANDLER = 'mvAppItemType::mvClickedHandler'
    DOUBLE_CLICKED_HANDLER = 'mvAppItemType::mvDoubleClickedHandler'
    DRAG_PAYLOAD = 'mvAppItemType::mvDragPayload'
    RESIZE_HANDLER = 'mvAppItemType::mvResizeHandler'

    # Шрифты и темы
    FONT = 'mvAppItemType::mvFont'
    FONT_REGISTRY = 'mvAppItemType::mvFontRegistry'
    FONT_RANGE_HINT = 'mvAppItemType::mvFontRangeHint'
    FONT_RANGE = 'mvAppItemType::mvFontRange'
    FONT_CHARS = 'mvAppItemType::mvFontChars'
    CHAR_REMAP = 'mvAppItemType::mvCharRemap'
    THEME = 'mvAppItemType::mvTheme'
    THEME_COLOR = 'mvAppItemType::mvThemeColor'
    THEME_STYLE = 'mvAppItemType::mvThemeStyle'
    THEME_COMPONENT = 'mvAppItemType::mvThemeComponent'

    # Текстуры и значения
    TEXTURE_REGISTRY = 'mvAppItemType::mvTextureRegistry'
    STATIC_TEXTURE = 'mvAppItemType::mvStaticTexture'
    DYNAMIC_TEXTURE = 'mvAppItemType::mvDynamicTexture'
    RAW_TEXTURE = 'mvAppItemType::mvRawTexture'
    VALUE_REGISTRY = 'mvAppItemType::mvValueRegistry'
    INT_VALUE = 'mvAppItemType::mvIntValue'
    FLOAT_VALUE = 'mvAppItemType::mvFloatValue'
    FLOAT4_VALUE = 'mvAppItemType::mvFloat4Value'
    INT4_VALUE = 'mvAppItemType::mvInt4Value'
    BOOL_VALUE = 'mvAppItemType::mvBoolValue'
    STRING_VALUE = 'mvAppItemType::mvStringValue'
    DOUBLE_VALUE = 'mvAppItemType::mvDoubleValue'
    DOUBLE4_VALUE = 'mvAppItemType::mvDouble4Value'
    COLOR_VALUE = 'mvAppItemType::mvColorValue'
    FLOAT_VECT_VALUE = 'mvAppItemType::mvFloatVectValue'
    SERIES_VALUE = 'mvAppItemType::mvSeriesValue'

    # Файлы
    FILE_DIALOG = 'mvAppItemType::mvFileDialog'
    FILE_EXTENSION = 'mvAppItemType::mvFileExtension'