from enum import Enum

class ThemeElement(Enum): pass

class CoreColors(ThemeElement):
    """Базовые цвета темы Dear PyGui (mvThemeCat_Core)"""
    TEXT = "mvThemeCol_Text"
    TEXT_DISABLED = "mvThemeCol_TextDisabled"
    WINDOW_BG = "mvThemeCol_WindowBg"
    CHILD_BG = "mvThemeCol_ChildBg"
    POPUP_BG = "mvThemeCol_PopupBg"
    BORDER = "mvThemeCol_Border"
    BORDER_SHADOW = "mvThemeCol_BorderShadow"
    FRAME_BG = "mvThemeCol_FrameBg"
    FRAME_BG_HOVERED = "mvThemeCol_FrameBgHovered"
    FRAME_BG_ACTIVE = "mvThemeCol_FrameBgActive"
    TITLE_BG = "mvThemeCol_TitleBg"
    TITLE_BG_ACTIVE = "mvThemeCol_TitleBgActive"
    TITLE_BG_COLLAPSED = "mvThemeCol_TitleBgCollapsed"
    MENU_BAR_BG = "mvThemeCol_MenuBarBg"
    SCROLLBAR_BG = "mvThemeCol_ScrollbarBg"
    SCROLLBAR_GRAB = "mvThemeCol_ScrollbarGrab"
    SCROLLBAR_GRAB_HOVERED = "mvThemeCol_ScrollbarGrabHovered"
    SCROLLBAR_GRAB_ACTIVE = "mvThemeCol_ScrollbarGrabActive"
    CHECK_MARK = "mvThemeCol_CheckMark"
    SLIDER_GRAB = "mvThemeCol_SliderGrab"
    SLIDER_GRAB_ACTIVE = "mvThemeCol_SliderGrabActive"
    BUTTON = "mvThemeCol_Button"
    BUTTON_HOVERED = "mvThemeCol_ButtonHovered"
    BUTTON_ACTIVE = "mvThemeCol_ButtonActive"
    HEADER = "mvThemeCol_Header"
    HEADER_HOVERED = "mvThemeCol_HeaderHovered"
    HEADER_ACTIVE = "mvThemeCol_HeaderActive"
    SEPARATOR = "mvThemeCol_Separator"
    SEPARATOR_HOVERED = "mvThemeCol_SeparatorHovered"
    SEPARATOR_ACTIVE = "mvThemeCol_SeparatorActive"
    RESIZE_GRIP = "mvThemeCol_ResizeGrip"
    RESIZE_GRIP_HOVERED = "mvThemeCol_ResizeGripHovered"
    RESIZE_GRIP_ACTIVE = "mvThemeCol_ResizeGripActive"
    TAB = "mvThemeCol_Tab"
    TAB_HOVERED = "mvThemeCol_TabHovered"
    TAB_ACTIVE = "mvThemeCol_TabActive"
    TAB_UNFOCUSED = "mvThemeCol_TabUnfocused"
    TAB_UNFOCUSED_ACTIVE = "mvThemeCol_TabUnfocusedActive"
    DOCKING_PREVIEW = "mvThemeCol_DockingPreview"
    DOCKING_EMPTY_BG = "mvThemeCol_DockingEmptyBg"
    PLOT_LINES = "mvThemeCol_PlotLines"
    PLOT_LINES_HOVERED = "mvThemeCol_PlotLinesHovered"
    PLOT_HISTOGRAM = "mvThemeCol_PlotHistogram"
    PLOT_HISTOGRAM_HOVERED = "mvThemeCol_PlotHistogramHovered"
    TABLE_HEADER_BG = "mvThemeCol_TableHeaderBg"
    TABLE_BORDER_STRONG = "mvThemeCol_TableBorderStrong"
    TABLE_BORDER_LIGHT = "mvThemeCol_TableBorderLight"
    TABLE_ROW_BG = "mvThemeCol_TableRowBg"
    TABLE_ROW_BG_ALT = "mvThemeCol_TableRowBgAlt"
    TEXT_SELECTED_BG = "mvThemeCol_TextSelectedBg"
    DRAG_DROP_TARGET = "mvThemeCol_DragDropTarget"
    NAV_HIGHLIGHT = "mvThemeCol_NavHighlight"
    NAV_WINDOWING_HIGHLIGHT = "mvThemeCol_NavWindowingHighlight"
    NAV_WINDOWING_DIM_BG = "mvThemeCol_NavWindowingDimBg"
    MODAL_WINDOW_DIM_BG = "mvThemeCol_ModalWindowDimBg"


class CoreStyles(ThemeElement):
    """Базовые стили размеров и скруглений (mvThemeCat_Core)"""
    ALPHA = "mvStyleVar_Alpha"
    DISABLED_ALPHA = "mvStyleVar_DisabledAlpha"
    WINDOW_PADDING = "mvStyleVar_WindowPadding"
    WINDOW_ROUNDING = "mvStyleVar_WindowRounding"
    WINDOW_BORDER_SIZE = "mvStyleVar_WindowBorderSize"
    WINDOW_MIN_SIZE = "mvStyleVar_WindowMinSize"
    WINDOW_TITLE_ALIGN = "mvStyleVar_WindowTitleAlign"
    CHILD_ROUNDING = "mvStyleVar_ChildRounding"
    CHILD_BORDER_SIZE = "mvStyleVar_ChildBorderSize"
    POPUP_ROUNDING = "mvStyleVar_PopupRounding"
    POPUP_BORDER_SIZE = "mvStyleVar_PopupBorderSize"
    FRAME_PADDING = "mvStyleVar_FramePadding"
    FRAME_ROUNDING = "mvStyleVar_FrameRounding"
    FRAME_BORDER_SIZE = "mvStyleVar_FrameBorderSize"
    ITEM_SPACING = "mvStyleVar_ItemSpacing"
    ITEM_INNER_SPACING = "mvStyleVar_ItemInnerSpacing"
    INDENT_SPACING = "mvStyleVar_IndentSpacing"
    CELL_PADDING = "mvStyleVar_CellPadding"
    SCROLLBAR_SIZE = "mvStyleVar_ScrollbarSize"
    SCROLLBAR_ROUNDING = "mvStyleVar_ScrollbarRounding"
    GRAB_MIN_SIZE = "mvStyleVar_GrabMinSize"
    GRAB_ROUNDING = "mvStyleVar_GrabRounding"
    TAB_ROUNDING = "mvStyleVar_TabRounding"
    TAB_BORDER_SIZE = "mvStyleVar_TabBorderSize"
    TAB_BAR_BORDER_SIZE = "mvStyleVar_TabBarBorderSize"
    TABLE_ANGLED_HEADERS_ANGLE = "mvStyleVar_TableAngledHeadersAngle"
    TABLE_ANGLED_HEADERS_TEXT_ALIGN = "mvStyleVar_TableAngledHeadersTextAlign"
    BUTTON_TEXT_ALIGN = "mvStyleVar_ButtonTextAlign"
    SELECTABLE_TEXT_ALIGN = "mvStyleVar_SelectableTextAlign"
    SEPARATOR_TEXT_BORDER_SIZE = "mvStyleVar_SeparatorTextBorderSize"
    SEPARATOR_TEXT_ALIGN = "mvStyleVar_SeparatorTextAlign"
    SEPARATOR_TEXT_PADDING = "mvStyleVar_SeparatorTextPadding"


class PlotColors(ThemeElement):
    """Цвета для графиков (mvThemeCat_Plots)"""
    LINE = "mvPlotCol_Line"
    FILL = "mvPlotCol_Fill"
    MARKER_OUTLINE = "mvPlotCol_MarkerOutline"
    MARKER_FILL = "mvPlotCol_MarkerFill"
    ERROR_BAR = "mvPlotCol_ErrorBar"
    FRAME_BG = "mvPlotCol_FrameBg"
    PLOT_BG = "mvPlotCol_PlotBg"
    PLOT_BORDER = "mvPlotCol_PlotBorder"
    LEGEND_BG = "mvPlotCol_LegendBg"
    LEGEND_BORDER = "mvPlotCol_LegendBorder"
    LEGEND_TEXT = "mvPlotCol_LegendText"
    TITLE_TEXT = "mvPlotCol_TitleText"
    INLAY_TEXT = "mvPlotCol_InlayText"
    AXIS_BG = "mvPlotCol_AxisBg"
    AXIS_BG_HOVERED = "mvPlotCol_AxisBgHovered"
    AXIS_BG_ACTIVE = "mvPlotCol_AxisBgActive"
    AXIS_GRID = "mvPlotCol_AxisGrid"
    AXIS_TEXT = "mvPlotCol_AxisText"
    SELECTION = "mvPlotCol_Selection"
    CROSSHAIRS = "mvPlotCol_Crosshairs"


class PlotStyles(ThemeElement):
    """Стили для графиков (mvThemeCat_Plots)"""
    LINE_WEIGHT = "mvPlotStyleVar_LineWeight"
    MARKER = "mvPlotStyleVar_Marker"
    MARKER_SIZE = "mvPlotStyleVar_MarkerSize"
    MARKER_WEIGHT = "mvPlotStyleVar_MarkerWeight"
    FILL_ALPHA = "mvPlotStyleVar_FillAlpha"
    ERROR_BAR_SIZE = "mvPlotStyleVar_ErrorBarSize"
    ERROR_BAR_WEIGHT = "mvPlotStyleVar_ErrorBarWeight"
    DIGITAL_BIT_HEIGHT = "mvPlotStyleVar_DigitalBitHeight"
    DIGITAL_BIT_GAP = "mvPlotStyleVar_DigitalBitGap"
    PLOT_BORDER_SIZE = "mvPlotStyleVar_PlotBorderSize"
    MINOR_ALPHA = "mvPlotStyleVar_MinorAlpha"
    MAJOR_TICK_LEN = "mvPlotStyleVar_MajorTickLen"
    MINOR_TICK_LEN = "mvPlotStyleVar_MinorTickLen"
    MAJOR_TICK_SIZE = "mvPlotStyleVar_MajorTickSize"
    MINOR_TICK_SIZE = "mvPlotStyleVar_MinorTickSize"
    MAJOR_GRID_SIZE = "mvPlotStyleVar_MajorGridSize"
    MINOR_GRID_SIZE = "mvPlotStyleVar_MinorGridSize"
    PLOT_PADDING = "mvPlotStyleVar_PlotPadding"
    LABEL_PADDING = "mvPlotStyleVar_LabelPadding"
    LEGEND_PADDING = "mvPlotStyleVar_LegendPadding"
    LEGEND_INNER_PADDING = "mvPlotStyleVar_LegendInnerPadding"
    LEGEND_SPACING = "mvPlotStyleVar_LegendSpacing"
    MOUSE_POS_PADDING = "mvPlotStyleVar_MousePosPadding"
    ANNOTATION_PADDING = "mvPlotStyleVar_AnnotationPadding"
    FIT_PADDING = "mvPlotStyleVar_FitPadding"
    PLOT_DEFAULT_SIZE = "mvPlotStyleVar_PlotDefaultSize"
    PLOT_MIN_SIZE = "mvPlotStyleVar_PlotMinSize"


class NodeColors(ThemeElement):
    """Цвета для Node Editor (mvThemeCat_Nodes)"""
    NODE_BACKGROUND = "mvNodeCol_NodeBackground"
    NODE_BACKGROUND_HOVERED = "mvNodeCol_NodeBackgroundHovered"
    NODE_BACKGROUND_SELECTED = "mvNodeCol_NodeBackgroundSelected"
    NODE_OUTLINE = "mvNodeCol_NodeOutline"
    TITLE_BAR = "mvNodeCol_TitleBar"
    TITLE_BAR_HOVERED = "mvNodeCol_TitleBarHovered"
    TITLE_BAR_SELECTED = "mvNodeCol_TitleBarSelected"
    LINK = "mvNodeCol_Link"
    LINK_HOVERED = "mvNodeCol_LinkHovered"
    LINK_SELECTED = "mvNodeCol_LinkSelected"
    PIN = "mvNodeCol_Pin"
    PIN_HOVERED = "mvNodeCol_PinHovered"
    BOX_SELECTOR = "mvNodeCol_BoxSelector"
    BOX_SELECTOR_OUTLINE = "mvNodeCol_BoxSelectorOutline"
    GRID_BACKGROUND = "mvNodeCol_GridBackground"
    GRID_LINE = "mvNodeCol_GridLine"


class NodeStyles(ThemeElement):
    """Стили для Node Editor (mvThemeCat_Nodes)"""
    GRID_SPACING = "mvNodeStyleVar_GridSpacing"
    NODE_CORNER_ROUNDING = "mvNodeStyleVar_NodeCornerRounding"
    NODE_PADDING_HORIZONTAL = "mvNodeStyleVar_NodePaddingHorizontal"
    NODE_PADDING_VERTICAL = "mvNodeStyleVar_NodePaddingVertical"
    NODE_BORDER_THICKNESS = "mvNodeStyleVar_NodeBorderThickness"
    LINK_THICKNESS = "mvNodeStyleVar_LinkThickness"
    LINK_LINE_SEGMENTS_PER_LENGTH = "mvNodeStyleVar_LinkLineSegmentsPerLength"
    LINK_HOVER_DISTANCE = "mvNodeStyleVar_LinkHoverDistance"
    PIN_CIRCLE_RADIUS = "mvNodeStyleVar_PinCircleRadius"
    PIN_QUAD_SIDE_LENGTH = "mvNodeStyleVar_PinQuadSideLength"
    PIN_TRIANGLE_SIDE_LENGTH = "mvNodeStyleVar_PinTriangleSideLength"
    PIN_LINE_THICKNESS = "mvNodeStyleVar_PinLineThickness"
    PIN_HOVER_RADIUS = "mvNodeStyleVar_PinHoverRadius"
    PIN_OFFSET = "mvNodeStyleVar_PinOffset"
